### ISSUE TITLE
[Feature Request] Complete Open-Source publishing

### ISSUE THREAD

**Issue by theDeniZ** [EXXETA/iOS-Security-Toolkit#1]
## Request Statement

The Version 1.0.0 of Mobile Security Toolkit uses a xcframework to make the Api of the package public. It has the caveat of having hidden code, which may not be trustworthy. 

Consider publishing whole package

## Solution Brainstorm

Publish the content of xcframework in current package

**Comment by theDeniZ** [comment]
Both Android and Flutter Mobile Security Toolkit is published as OpenSource, no private parts required. Publishing of iOS Security Toolkit shall commence now 🎆

**Comment by theDeniZ** [comment]
@ychoura

**Comment by ychoura** [comment]
PR is open !5
